# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('state', models.CharField(default='in progress', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('colored', models.BooleanField(default=False)),
                ('style', models.CharField(default='', max_length=255)),
                ('temporary', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='../../')),
            ],
        ),
        migrations.CreateModel(
            name='TattooStudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('place', models.TextField(default='shoulder')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tattoo.Studio')),
                ('tattoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tattoo.Tattoo')),
            ],
        ),
        migrations.AddField(
            model_name='deal',
            name='tatooStudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tattoo.TattooStudio'),
        ),
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
