# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0002_auto_20171204_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TattooImageUpload',
            new_name='TattooImage',
        ),
    ]
