# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0003_auto_20171205_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattoo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tattoostudio',
            name='place',
        ),
        migrations.AddField(
            model_name='tattoo',
            name='place',
            field=models.TextField(default='shoulder'),
        ),
        migrations.AddField(
            model_name='tattooimage',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
