# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0005_auto_20171205_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattoostudio',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='tattoostudio',
            name='tattoo',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='tattoo_studio',
        ),
        migrations.AddField(
            model_name='deal',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tattoo.Studio'),
        ),
        migrations.AddField(
            model_name='deal',
            name='tattoo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tattoo.Tattoo'),
        ),
        migrations.DeleteModel(
            name='TattooStudio',
        ),
    ]
