# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-10 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0006_auto_20171208_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studio',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
