# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 06:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tattoo', '0007_auto_20171210_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattooimage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='image',
        ),
        migrations.AddField(
            model_name='tattoo',
            name='image_file',
            field=models.ImageField(default='/home/jops/university/refactoring/vtattoo/media/tattooimg/cup.jpg', storage=django.core.files.storage.FileSystemStorage('/home/jops/university/refactoring/vtattoo/media/tattooimg'), upload_to=''),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TattooImage',
        ),
    ]
