# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0008_auto_20171212_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='user',
        ),
    ]
