# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0010_tattoo_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tattoo',
            options={'ordering': ('created',)},
        ),
    ]
