# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-12 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0011_auto_20171212_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattoo',
            name='colored',
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tattoo',
            name='temporary',
        ),
        migrations.AddField(
            model_name='deal',
            name='colored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deal',
            name='place',
            field=models.TextField(default='shoulder'),
        ),
        migrations.AddField(
            model_name='deal',
            name='temporary',
            field=models.BooleanField(default=False),
        ),
    ]
