# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tattoo', '0012_auto_20171212_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tattoo',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
