# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0013_auto_20171215_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
