# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0014_auto_20171215_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_code',
            field=models.CharField(default='11111111111111111111', max_length=30),
        ),
    ]
