# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo', '0015_deal_deal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='colored_price',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='studio',
            name='regular_price',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='studio',
            name='temp_col_price',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='studio',
            name='temporary_price',
            field=models.FloatField(default=-1),
        ),
    ]
